### PR TITLE
Include "support" channels as well

### PR DESCRIPTION
**Pull request by MeerBiene**
Tracks time spent in support channels as well as in channels with "ticket" in their names

### CODE REVIEW

**Comment by LoneDev6** [comment]
Hello, I can't merge this in this repository because it's a generic plugin.
Not all servers use "support" to identify tickets category and may create confusion because imagine a category named "Support the server", this will be wrongly considered a tickets category.

A better idea would be adding a config for the plugin menu that allows to input channel ids and category ids and then change the logic to take ids into account instead of the name

**Comment by MeerBiene** [comment]
you're right, I didn't consider that. I will look into a config and maybe allow to either submit a name or id and maybe the matching type (either exact or just includes)

**Comment by LoneDev6** [comment]
i'm not experienced with BetterDiscord api but I've seen that it's possible to create a settings screen.
A settings screen that allows to add any channel or category id would do the trick :D

**Comment by MeerBiene** [comment]
same but i found something where its implemented where i can get some inspiration https://github.com/rauenzi/BetterDiscordAddons/blob/master/Plugins/DoNotTrack/DoNotTrack.plugin.js#L107-L119

**Comment by LoneDev6** [comment]
This would also fix this bug: if you open support tickets on another server in which you're not an admin you will get time tracked anyway.
IDs check will solve this

**Comment by MeerBiene** [comment]
There seems to be a problem, as of now, I can only set basic toggles to the settings menu, so no text input, I'll try to see if I can get it working with modals.

**Comment by LoneDev6** [comment]
immagine
Code is exactly here, it's this big json configuration file: https://github.com/rauenzi/BetterDiscordAddons/blob/master/Plugins/BetterFormattingRedux/BetterFormattingRedux.plugin.js#L36

You can format it using https://jsonformatter.curiousconcept.com/

Then get the value using this.settings.VARIABLE.

If you have no time to work on that I can do it the next week

**Comment by MeerBiene** [comment]
oh, i love finding out i was stupid again :D i remember thinking "mh there has to be some way to get more that a toggle switch".. anyways, now that i have information ill slap it in

**Comment by LoneDev6** [comment]
Very nice! :D

**Pull request merged**
